---
title: btep - bringing together extraordinary people
baseurl: "/"
permalink: "/:title/"
palette: orange
header:
  title: btep
  logo_img: "/images/bteplogoWEB.png"
  has_nav: true
  menu:
    actions:
    - label: Donate
      url: "/donate"
    - label: Register
      url: https://www.tourneymachine.com/E65074
footer:
  logo_img: "/images/bteplogoCMS.png"
  tagline: bringing together extraordinary people
  has_nav: true
  nav_title: Organization
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest events.
  content: "&copy; 2019 BTEP, INC. All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
